### ISSUE TITLE
 /usr/local/bin/aad-login failed: exit code 1

### ISSUE THREAD

**Issue by laclasse** [bureado/aad-login#1]
CentOS 7.X:
Certainly due to having the pam rule inserted in multiples pam.d files, but just thought i would report it.
This is absolutely not critical as the login succeeds in any case, just the cosmetic 'usr/local/bin/aad-login failed: exit code 1' at all login and sudo auths, as below:

login as: <user>
<user>@<hostname> password:
/usr/local/bin/aad-login failed: exit code 1

$ sudo -i
[sudo] password for <user>
/usr/local/bin/aad-login failed: exit code 1

**Comment by bureado** [comment]
Thanks for looking into this back in the day and hope it was useful. I'm deprecating this experiment (long overdue) with https://docs.microsoft.com/en-us/azure/virtual-machines/linux/login-using-aad in preview.
