### ISSUE TITLE
Handle multi-factor authentication

### ISSUE THREAD

**Issue by igorgatis** [bureado/aad-login#4]
When multi-authentication is enabled for a given user, this script fails with:

```
{ error: 'interaction_required',
  error_description: 'AADSTS50076: Due to a configuration change made by your administrator,
  or because you moved to a new location, you must use multi-factor authentication to access
  \'00000002-0000-0000-c000-000000000000\'...',
  error_codes: [ 50076 ],
  ...
}
```

**Comment by bureado** [comment]
Thanks for even looking into this back in the day. With [Azure Active Directory authentication for Linux](https://docs.microsoft.com/en-us/azure/virtual-machines/linux/login-using-aad) in preview (which handles MFA) this entire thing is not needed anymore. Thanks!

**Comment by Jnchi** [comment]
See also:

- https://github.com/CyberNinjas/pam_aad
- https://github.com/CyberNinjas/libnss_aad
