### ISSUE TITLE
Perhaps change /usr/local/bin/aad-login to use "nodejs" instead of "node"

### ISSUE THREAD

**Issue by igorgatis** [bureado/aad-login#5]
I'm using aad-login in a `Ubuntu 16.04.1 LTS` machine. I installed Node.Js and npm by running `sudo apt-get install nodejs npm`. The command `node` is not available so aad-login was failing. I changed `/usr/local/bin/aad-login` to `nodejs` and everything worked just fine.

Perhaps this script should be smart enough to choose one or the other automatically.

**Comment by bureado** [comment]
Thanks for looking into this back in the day and hope it was useful. Since I'm deprecating this (long overdue) I added a note to `README.md` as a known issue.
